// See https://aka.ms/new-console-template for more information
Console.SetCursorPosition(10, 2);
Console.BackgroundColor = ConsoleColor.Red;
Console.Write("   "); 
Console.SetCursorPosition(13, 2);
Console.BackgroundColor = ConsoleColor.Red;
Console.Write("   ");
Console.SetCursorPosition(16, 2);
Console.BackgroundColor = ConsoleColor.Red;
Console.Write("   ");
Console.SetCursorPosition(9, 3);
Console.BackgroundColor = ConsoleColor.Red;
Console.Write("   ");
Console.SetCursorPosition(12, 3);
Console.BackgroundColor = ConsoleColor.Red;
Console.Write("   ");
Console.SetCursorPosition(15, 3);
Console.BackgroundColor = ConsoleColor.Black;
Console.Write("   ");
Console.SetCursorPosition(18, 3);
Console.BackgroundColor = ConsoleColor.Black;
Console.Write("   ");
Console.SetCursorPosition(8, 4);
Console.BackgroundColor = ConsoleColor.Black;
Console.Write("   ");
Console.SetCursorPosition(11, 4);
Console.BackgroundColor = ConsoleColor.Black;
Console.Write("   ");
Console.SetCursorPosition(14, 4);
Console.BackgroundColor = ConsoleColor.DarkYellow; 
Console.Write("   ");
Console.SetCursorPosition(17, 4);
Console.BackgroundColor = ConsoleColor.DarkYellow;
Console.Write("   ");
Console.SetCursorPosition(8, 5);
Console.BackgroundColor = ConsoleColor.DarkYellow;
Console.Write("   ");
Console.SetCursorPosition(11, 5);
Console.BackgroundColor = ConsoleColor.DarkYellow;
Console.Write("   ");
Console.SetCursorPosition(14, 5);
Console.BackgroundColor = ConsoleColor.DarkYellow;
Console.Write("   ");
Console.SetCursorPosition(17, 5);
Console.BackgroundColor = ConsoleColor.DarkYellow;
Console.Write("   ");
Console.SetCursorPosition(20, 5);
Console.BackgroundColor = ConsoleColor.DarkYellow;
Console.Write("   ");
Console.SetCursorPosition(9, 6);
Console.BackgroundColor = ConsoleColor.Blue; 
Console.Write("   ");
Console.SetCursorPosition(12, 6);
Console.BackgroundColor = ConsoleColor.Blue;
Console.Write("   ");
Console.SetCursorPosition(15, 6);
Console.BackgroundColor = ConsoleColor.Red; 
Console.Write("   ");
Console.SetCursorPosition(18, 6);
Console.BackgroundColor = ConsoleColor.Red;
Console.Write("   ");
Console.SetCursorPosition(9, 7);
Console.BackgroundColor = ConsoleColor.Red;
Console.Write("   ");
Console.SetCursorPosition(12, 7);
Console.BackgroundColor = ConsoleColor.Red;
Console.Write("   ");
Console.SetCursorPosition(15, 7);
Console.BackgroundColor = ConsoleColor.DarkYellow; 
Console.Write("   ");
Console.SetCursorPosition(18, 7);
Console.BackgroundColor = ConsoleColor.DarkYellow;
Console.Write("   ");
Console.SetCursorPosition(10, 8);
Console.BackgroundColor = ConsoleColor.Red; 
Console.Write("   ");
Console.SetCursorPosition(13, 8);
Console.BackgroundColor = ConsoleColor.Red;
Console.Write("   ");
Console.SetCursorPosition(16, 8);
Console.BackgroundColor = ConsoleColor.DarkRed; 
Console.Write("   ");
Console.SetCursorPosition(19, 8);
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write("   ");
Console.ResetColor();
Console.SetCursorPosition(0, 10);
